version: 2.1

commands:
  print_pipeline_id:
    description: "A very simple command to suck my dick"
    parameters:
      to:
        type: string
    steps:
      - run: echo << parameters.to >>

jobs:
  say-hello:
   
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello"
      - print_pipeline_id:
          to: <<pipeline.id>>

workflows:
  say-hello-workflow:
    jobs:
      - say-hello
