version: 2.1

commands:
  fuck-you:
    description: "A very simple command to suck my dick"
    parameters:
      to:
        type: string
        default: "fuck you"
    steps:
      - run: echo << parameters.to >>

jobs:
  say-hello:
   
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello"
      - fuck-you:
          to: "MOTHER FUCKER"

workflows:
  say-hello-workflow:
    jobs:
      - say-hello
